### ISSUE TITLE
Multiple Cards

### ISSUE THREAD

**Issue by dmastag** [florianbepunkt/ionic-angular-swing#1]
Any chance to extend the example to have multiple cards like in the original Swing Example?

**Comment by florianbepunkt** [comment]
this is already possible. as you see in home.ts we have an array that holds our cards

cards: Array<any>;

basically you can add as many elements to this array as you like. adding new cards happens in two places: in our `ngAfterViewInit()` method and in our `voteUp()` method. in both we call an `addNewCards(count: number)` method. If you pass a higher count argument to the method more that 1 card is added.

does this solve your issue?

**Comment by dmastag** [comment]
Yes, it does.
Thanks
